# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node CI

# 触发workflow的条件
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器私钥
    SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
    USER_NAME: ${{ secrets.USER_NAME }} # 服务器用户名
    VITE_SERVER_NAME: ${{ secrets.VITE_SERVER_NAME }} 
    cache-name: note
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.2]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
     #缓存依赖
    - name: Cache nodemodules
      uses: actions/cache@v1
      env:
          cache-name: cache-node-modules
      with:
          # 需要缓存的文件的路径
          path: ./node_modules 
          # 对缓存的文件指定的唯一标识
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }} 
          # 用于没有再找目标key的缓存的backup选项
          restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
    # 装依赖
    - name: Install
      run: |
          npm install -g yarn@1.22.19
          yarn install
    # 打包
    - name: Build
      run: |
          echo "VITE_SERVER_NAME = ${{ env.VITE_SERVER_NAME }}" > .env
          yarn build
     # 上传打包资源
    - name: Deploy
      uses: easingthemes/ssh-deploy@v3
      env:
          SSH_PRIVATE_KEY: ${{ env.SERVER_PRIVATE_KEY }}
          ARGS: '-avz --delete'
          SOURCE: '.output/'
          REMOTE_HOST: ${{ env.SERVER_HOST }}
          REMOTE_USER: ${{ env.USER_NAME }}
          TARGET: /root/i-lion-front/.output # 服务器目标路径
    # 重新部署
    - name: Reload pm2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.USER_NAME }}
        key: ${{ env.SERVER_PRIVATE_KEY }}
        script: |
          source /www/server/nvm/nvm.sh
          nvm use 18.18.2
          zsh /root/i-lion-front/run_node.sh
